// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdsIAFF-yuGmJ18L84WF36S0R3eH72qyU',
    appId: '1:914973413698:web:73b78d13c7e99c51d3f8db',
    messagingSenderId: '914973413698',
    projectId: 'e-commarce-d9427',
    authDomain: 'e-commarce-d9427.firebaseapp.com',
    storageBucket: 'e-commarce-d9427.appspot.com',
    measurementId: 'G-QDTJB4C7HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdgYWivf-WQrmFng-5gTB-QAVErulZTp0',
    appId: '1:914973413698:android:1fb53cc578eb0c12d3f8db',
    messagingSenderId: '914973413698',
    projectId: 'e-commarce-d9427',
    storageBucket: 'e-commarce-d9427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0hdED-jMSq5vLuWa6G_R_8evhOQvVcg',
    appId: '1:914973413698:ios:51af74fc0db0e4d0d3f8db',
    messagingSenderId: '914973413698',
    projectId: 'e-commarce-d9427',
    storageBucket: 'e-commarce-d9427.appspot.com',
    iosClientId: '914973413698-i9n8iou941iv61e1bqlufvfqeug3sd47.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
